// src/lib/search-data.ts
import type { SearchItem } from './search-types'

export const SEARCH_DATA: SearchItem[] = [
  // --- Learning Paths (5) ---
  {
    id: 'path-1',
    type: 'path',
    title: 'AI for Absolute Beginners',
    excerpt: 'Start with zero assumptions. 8 lessons from what AI is to using it daily.',
    category: 'Learning Path',
    href: '/paths/ai-for-beginners',
    difficulty: 'beginner',
  },
  {
    id: 'path-2',
    type: 'path',
    title: 'Master Agentic AI',
    excerpt: 'Go deep on agents, tool use, memory, and planning. 14 lessons.',
    category: 'Learning Path',
    href: '/paths/master-agentic-ai',
    difficulty: 'intermediate',
  },
  {
    id: 'path-3',
    type: 'path',
    title: 'Build Your First AI Agent',
    excerpt: 'Go from one tool call to a working autonomous agent. 10 lessons.',
    category: 'Learning Path',
    href: '/paths/build-first-agent',
    difficulty: 'beginner',
  },
  {
    id: 'path-4',
    type: 'path',
    title: 'Prompt Engineering Essentials',
    excerpt: 'Write prompts that actually work. 6 lessons covering the core techniques.',
    category: 'Learning Path',
    href: '/paths/prompt-engineering',
    difficulty: 'beginner',
  },
  {
    id: 'path-5',
    type: 'path',
    title: 'Beginner to AI Engineer',
    excerpt: 'The full journey from AI basics to shipping production-grade AI apps. 24 lessons.',
    category: 'Learning Path',
    href: '/paths/beginner-to-engineer',
    difficulty: 'advanced',
  },

  // --- Articles (10) ---
  {
    id: 'article-1',
    type: 'article',
    title: 'What is an AI Agent?',
    excerpt: 'The line between a chatbot and an agent comes down to one thing: the ability to take actions.',
    category: 'Agentic AI',
    href: '/library/agentic-ai/what-is-an-agent',
    difficulty: 'beginner',
  },
  {
    id: 'article-2',
    type: 'article',
    title: 'Tool Use: Giving Models Hands',
    excerpt: 'Function calling turns a language model from a talker into a doer. Here is how it works.',
    category: 'Agentic AI',
    href: '/library/agentic-ai/tool-use-explained',
    difficulty: 'intermediate',
  },
  {
    id: 'article-3',
    type: 'article',
    title: 'How LLMs Actually Work',
    excerpt: 'Tokens, attention, and the transformer architecture explained without the jargon.',
    category: 'Large Language Models',
    href: '/library/large-language-models/how-llms-work',
    difficulty: 'beginner',
  },
  {
    id: 'article-4',
    type: 'article',
    title: 'What is AI? A Clear, Honest Explainer',
    excerpt: 'AI is not magic or a robot uprising. Here is what it actually is and why it matters now.',
    category: 'AI Foundations',
    href: '/library/ai-foundations/what-is-ai',
    difficulty: 'beginner',
  },
  {
    id: 'article-5',
    type: 'article',
    title: 'RAG Without the Hype',
    excerpt: 'Retrieval-augmented generation is simple in principle and finicky in practice. A clear guide.',
    category: 'Agentic AI',
    href: '/library/agentic-ai/rag-explained',
    difficulty: 'beginner',
  },
  {
    id: 'article-6',
    type: 'article',
    title: 'Prompt Engineering Fundamentals',
    excerpt: 'The core techniques behind writing prompts that reliably get the output you want.',
    category: 'Building with AI',
    href: '/library/building-with-ai/prompt-engineering',
    difficulty: 'beginner',
  },
  {
    id: 'article-7',
    type: 'article',
    title: 'Memory in AI Agents: Types and Trade-offs',
    excerpt: 'In-context, external, and procedural memory — when to use each and what it costs.',
    category: 'Agentic AI',
    href: '/library/agentic-ai/agent-memory',
    difficulty: 'intermediate',
  },
  {
    id: 'article-8',
    type: 'article',
    title: 'Understanding Embeddings',
    excerpt: 'Embeddings turn words and documents into numbers that capture meaning. Here is the intuition.',
    category: 'Large Language Models',
    href: '/library/large-language-models/embeddings',
    difficulty: 'intermediate',
  },
  {
    id: 'article-9',
    type: 'article',
    title: 'AI Ethics: Key Principles',
    excerpt: 'Fairness, accountability, transparency, and safety — the principles that should guide AI development.',
    category: 'Ethics & Safety',
    href: '/library/ethics-safety/ai-ethics-principles',
    difficulty: 'beginner',
  },
  {
    id: 'article-10',
    type: 'article',
    title: 'Fine-tuning vs Prompting',
    excerpt: 'When to fine-tune a model and when a well-crafted prompt is all you need.',
    category: 'Large Language Models',
    href: '/library/large-language-models/fine-tuning-vs-prompting',
    difficulty: 'intermediate',
  },

  // --- Glossary (5) ---
  {
    id: 'glossary-1',
    type: 'glossary',
    title: 'LLM',
    excerpt: 'Large Language Model — a neural network trained on text to predict and generate language.',
    category: 'Glossary',
    href: '/glossary/llm',
  },
  {
    id: 'glossary-2',
    type: 'glossary',
    title: 'RAG',
    excerpt: 'Retrieval-Augmented Generation — grounding model outputs with retrieved external documents.',
    category: 'Glossary',
    href: '/glossary/rag',
  },
  {
    id: 'glossary-3',
    type: 'glossary',
    title: 'Agent',
    excerpt: 'An AI system that perceives its environment and takes actions to achieve a goal autonomously.',
    category: 'Glossary',
    href: '/glossary/agent',
  },
  {
    id: 'glossary-4',
    type: 'glossary',
    title: 'Embedding',
    excerpt: 'A dense numerical vector that represents the semantic meaning of a piece of text.',
    category: 'Glossary',
    href: '/glossary/embedding',
  },
  {
    id: 'glossary-5',
    type: 'glossary',
    title: 'Fine-tuning',
    excerpt: 'Further training a pre-trained model on a domain-specific dataset to improve task performance.',
    category: 'Glossary',
    href: '/glossary/fine-tuning',
  },
]
