// src/lib/search-data.ts
import type { SearchItem } from './search-types'

export const SEARCH_DATA: SearchItem[] = [
  // --- Learning Paths ---
  {
    id: 'path-1',
    type: 'path',
    title: 'Getting Started',
    excerpt: 'Everything you need before you build anything — Terminal, Python, Git, APIs, and deployment. 101 topics.',
    category: 'Learning Path',
    href: '/paths/getting-started',
    difficulty: 'beginner',
  },

  // --- Articles (Module 1) ---
  {
    id: 'article-1',
    type: 'article',
    title: 'What AI Actually Is — and What It Is Not',
    excerpt: 'AI is not magic or a robot uprising. Here is what it actually is and why it matters now.',
    category: 'AI Foundations',
    href: '/library/ai-foundations/what-is-ai',
    difficulty: 'beginner',
  },
  {
    id: 'article-2',
    type: 'article',
    title: 'The AI Family Tree: From Machine Learning to Agentic AI',
    excerpt: 'How the different branches of AI relate to each other and where things are heading.',
    category: 'AI Foundations',
    href: '/library/ai-foundations/ai-family-tree',
    difficulty: 'beginner',
  },
  {
    id: 'article-3',
    type: 'article',
    title: 'How Large Language Models Actually Work',
    excerpt: 'Tokens, attention, and the transformer architecture explained without the jargon.',
    category: 'Large Language Models',
    href: '/library/large-language-models/how-llms-work',
    difficulty: 'beginner',
  },
  {
    id: 'article-4',
    type: 'article',
    title: "Chatbot vs AI Agent: What's Actually the Difference?",
    excerpt: 'The line between a chatbot and an agent comes down to one thing: the ability to take actions.',
    category: 'Agentic AI',
    href: '/library/agentic-ai/chatbot-vs-agent',
    difficulty: 'beginner',
  },
  {
    id: 'article-5',
    type: 'article',
    title: 'ChatGPT vs Claude vs Gemini vs Grok',
    excerpt: 'What makes each model different, and how to choose the right one for your use case.',
    category: 'AI Tools',
    href: '/library/ai-tools/chatgpt-vs-claude-vs-gemini',
    difficulty: 'beginner',
  },
  {
    id: 'article-6',
    type: 'article',
    title: 'Free AI Tools for Beginners',
    excerpt: 'The tools you actually need to get started — and the ones you can skip.',
    category: 'AI Foundations',
    href: '/library/ai-foundations/free-ai-tools-to-start',
    difficulty: 'beginner',
  },
  {
    id: 'article-7',
    type: 'article',
    title: 'AI Tools You Already Use Every Day',
    excerpt: 'Spell check, autocomplete, recommendations — AI has been in your life longer than you think.',
    category: 'AI Foundations',
    href: '/library/ai-foundations/ai-tools-you-already-use',
    difficulty: 'beginner',
  },
  {
    id: 'article-8',
    type: 'article',
    title: "How to Think About AI: A Beginner's Mindset Guide",
    excerpt: 'The mental models that make learning AI click — and the ones that hold people back.',
    category: 'AI Foundations',
    href: '/library/ai-foundations/how-to-think-about-ai',
    difficulty: 'beginner',
  },

  // --- Glossary (5) ---
  {
    id: 'glossary-1',
    type: 'glossary',
    title: 'LLM',
    excerpt: 'Large Language Model — a neural network trained on text to predict and generate language.',
    category: 'Glossary',
    href: '/glossary/llm',
  },
  {
    id: 'glossary-2',
    type: 'glossary',
    title: 'RAG',
    excerpt: 'Retrieval-Augmented Generation — grounding model outputs with retrieved external documents.',
    category: 'Glossary',
    href: '/glossary/rag',
  },
  {
    id: 'glossary-3',
    type: 'glossary',
    title: 'Agent',
    excerpt: 'An AI system that perceives its environment and takes actions to achieve a goal autonomously.',
    category: 'Glossary',
    href: '/glossary/agent',
  },
  {
    id: 'glossary-4',
    type: 'glossary',
    title: 'Embedding',
    excerpt: 'A dense numerical vector that represents the semantic meaning of a piece of text.',
    category: 'Glossary',
    href: '/glossary/embedding',
  },
  {
    id: 'glossary-5',
    type: 'glossary',
    title: 'Fine-tuning',
    excerpt: 'Further training a pre-trained model on a domain-specific dataset to improve task performance.',
    category: 'Glossary',
    href: '/glossary/fine-tuning',
  },
]
